image: node:8
pipelines:
  branches:
    develop:
    - step:
        name: Install and Build
        script:
          - yarn
          - yarn build
     - step:
        name: Deploy to QA
        deployment: production   # can be test, staging or production
        trigger: manual  # uncomment to make manual deployment
        script:
          - rsync clvrz -e dist/ $PRODUCTION_DEPLOY_URL