image: node:9.8.0
pipelines:
  branches:
    develop:
    - step:
        name: Install and Build
        script:
          - yarn
          - yarn build-towerstone
    - step:
        name: Deploy to QA
        deployment: production   # can be test, staging or production
        trigger: manual  # uncomment to make manual deployment
        script:
          - rsync clvrz -e build/ $PRODUCTION_DEPLOY_URL