image: node:9.8.0
pipelines:
  branches:
    develop:
    - step:
        name: Install and Build TowerStone
        script:
          - npm install
          - npm run build-towerstone
    - step:
        name: Deploy TowerStone to QA
        deployment: staging   # can be test, staging or production
        trigger: manual  # uncomment to make manual deployment
        script:
          - rsync clvrz -e build/ $QA_DEPLOY_ROOT/towerstone