import React from 'react';
// export all your widgets here in order for them to be bound to the form registry and available for use.
export { default as AutoCompleteDropDown } from './AutoCompleteDropDown/AutoCompleteDropDown';
export { default as AutoCompleteWidget } from './AutoCompleteDropDown/AutoCompleteDropDown';
export { BarChartWidgetComponent as BarChartWidget } from './ChartWidget';
export { default as ChipArrayWidget } from './ChipArray';
export { default as ConditionalIconWidget } from './ConditionalIconWidget';
export { default as ColumnFilterWidget } from './ColumnFilterWidget';
export { default as ColumnSelectorWidget } from './ColumnSelectorWidget';
export { default as CompanyLogoWidget } from './CompanyLogo';
export { default as ContentWidget } from './ContentWidget/ContentWidget';
export { ComposedChartWidgetComponent as ComposedChartWidget} from './ChartWidget';
export { default as DataPageWidget } from './DataPageWidget';
export { default as DateSelectorWidget } from '@reactory/client-core/components/dates/DateSelector';
export { DateWidget } from './DateSelector';
export { default as FroalaWidget } from './Froala/FroalaWidget';
export { FunnelChartWidgetComponent as FunnelChartWidget} from './ChartWidget';
export const HiddenWidget = (props, context) => (<input type="hidden" name={props.name} value={props.formData} />);
export { default as LabelWidget } from './LabelWidget';
export { default as LineChartWidget } from './Charts/LineChartWidget';
export { default as LinkField } from './LinkFieldWidget'; //added for backward compatibility
export { default as LinkFieldWidget } from './LinkFieldWidget';
export { default as MaterialListWidget } from './MaterialListWidget';
export { MaterialTableWidget } from './MaterialTableWidget';
export { PieChartWidgetComponent as PieChartWidget } from './ChartWidget';
export { ProgressWidgetComponent as ProgressWidget } from './ProgressWidget';
export { default as ReactoryColorPicker } from './ReactoryColorPicker';
export { default as ReactoryD3Widget } from './D3/ReactoryD3Renderer';
export { default as ReactoryDropZoneWidget } from './ReactoryDropZone';
export { default as ReactoryGoogleMapWidget } from './mapping/GoogleMapWidget';
export { default as ReactoryImageWidget } from './ImageWidget';
export { default as ImageWidget } from './ImageWidget';
export { default as RecordLookupWidget } from './RecordLookup';
export { default as RichEditorWidget } from './RichEditor';
export { default as SchemaSelectorWidget } from './SchemaSelectorWidget';
export { default as SearchWidget } from './SearchWidget';
export { default as SelectWidget } from './Select';
export { default as SelectWithDataWidget } from './SelectWithData';
export { default as SliderWidget } from './SliderWidget';
export { StaticContentWidget } from './StaticContentWidget';
export { default as StepperWidget } from './StepperWidget';
export { default as ToolbarWidget } from './ToolbarWidget';
export { default as ReactorChatButtonWidget } from './ReactorChatButtonWidget';
export const UserListItemWidget = (props, context) => {
  return (<>Complete Import from reactory-user pluging</>)
};
export { default as UserSelectorWidget } from './UserSelectorWidget';
export { default as UserWidgetWithSearch } from './UserWidgetWithSearch';
export { default as WidgetNotAvailable } from './WidgetNotAvailable';
export { default as CardWidget } from './CardWidget/CardWidget';